export enum ActionType {
  ADD_TO_CART = 'ADD_TO_CART',
  REMOVE_FROM_CART = 'REMOVE_FROM_CART',
  CLEAR_THE_CART = 'CLEAR_THE_CART',
  LOG_IN_SUCCESS = 'LOG_IN/SUCCESS',
  LOG_IN_PENDING = 'LOG_IN/PENDING',
  LOG_IN_ERROR = 'LOG_IN/ERROR',
  LOG_OUT = 'LOG_OUT',
}
